spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root@123
      database: users
      authentication-database: admin
     

server:
  port: 8080
